/* Generated by Cython 0.9.6.12 on Sat Feb 14 21:33:59 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef WIN32
  #define __stdcall
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "hidserv.c"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from hidserver */



/* Implementation of hidserver */

/* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":12
 * 
 * 
 * def init_hidserver():             # <<<<<<<<<<<<<< 
 * 
 *    init_server()
 */

static PyObject *__pyx_pf_9hidserver_init_hidserver(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9hidserver_init_hidserver(PyObject *__pyx_self, PyObject *unused) {
  PyObject *__pyx_r;

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":14
 * def init_hidserver():
 * 
 *    init_server()             # <<<<<<<<<<<<<< 
 *    
 * 
 */
  init_server();

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":17
 *    
 * 
 * def send_event_key(mod, val):             # <<<<<<<<<<<<<< 
 * 
 *    n = send_event(mod,val)
 */

static PyObject *__pyx_pf_9hidserver_send_event_key(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_9hidserver_send_event_key(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_mod = 0;
  PyObject *__pyx_v_val = 0;
  PyObject *__pyx_v_n;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"mod","val",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_mod = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_val = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_mod, &__pyx_v_val))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  return NULL;
  __pyx_L3:;
  Py_INCREF(__pyx_v_mod);
  Py_INCREF(__pyx_v_val);
  __pyx_v_n = Py_None; Py_INCREF(Py_None);

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":19
 * def send_event_key(mod, val):
 * 
 *    n = send_event(mod,val)             # <<<<<<<<<<<<<< 
 *    return n
 * 
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_mod); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_val); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(send_event(__pyx_1, __pyx_2)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_3;
  __pyx_3 = 0;

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":20
 * 
 *    n = send_event(mod,val)
 *    return n             # <<<<<<<<<<<<<< 
 * 
 * def send_mouse_ev(btn,mov_x,mov_y,whell):
 */
  Py_INCREF(__pyx_v_n);
  __pyx_r = __pyx_v_n;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("hidserver.send_event_key");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  Py_DECREF(__pyx_v_mod);
  Py_DECREF(__pyx_v_val);
  return __pyx_r;
}

/* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":22
 *    return n
 * 
 * def send_mouse_ev(btn,mov_x,mov_y,whell):             # <<<<<<<<<<<<<< 
 * 
 *   n = send_mouse_event(btn,mov_x,mov_y,whell)
 */

static PyObject *__pyx_pf_9hidserver_send_mouse_ev(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_9hidserver_send_mouse_ev(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_btn = 0;
  PyObject *__pyx_v_mov_x = 0;
  PyObject *__pyx_v_mov_y = 0;
  PyObject *__pyx_v_whell = 0;
  PyObject *__pyx_v_n;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  int __pyx_3;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"btn","mov_x","mov_y","whell",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 4)) {
    __pyx_v_btn = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_mov_x = PyTuple_GET_ITEM(__pyx_args, 1);
    __pyx_v_mov_y = PyTuple_GET_ITEM(__pyx_args, 2);
    __pyx_v_whell = PyTuple_GET_ITEM(__pyx_args, 3);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_btn, &__pyx_v_mov_x, &__pyx_v_mov_y, &__pyx_v_whell))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  return NULL;
  __pyx_L3:;
  Py_INCREF(__pyx_v_btn);
  Py_INCREF(__pyx_v_mov_x);
  Py_INCREF(__pyx_v_mov_y);
  Py_INCREF(__pyx_v_whell);
  __pyx_v_n = Py_None; Py_INCREF(Py_None);

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":24
 * def send_mouse_ev(btn,mov_x,mov_y,whell):
 * 
 *   n = send_mouse_event(btn,mov_x,mov_y,whell)             # <<<<<<<<<<<<<< 
 *   return n
 * 
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_btn); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_mov_x); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_3 = __pyx_PyInt_int(__pyx_v_mov_y); if (unlikely((__pyx_3 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_4 = __pyx_PyInt_int(__pyx_v_whell); if (unlikely((__pyx_4 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(send_mouse_event(__pyx_1, __pyx_2, __pyx_3, __pyx_4)); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_5;
  __pyx_5 = 0;

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":25
 * 
 *   n = send_mouse_event(btn,mov_x,mov_y,whell)
 *   return n             # <<<<<<<<<<<<<< 
 * 
 * def connec_state():
 */
  Py_INCREF(__pyx_v_n);
  __pyx_r = __pyx_v_n;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("hidserver.send_mouse_ev");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  Py_DECREF(__pyx_v_btn);
  Py_DECREF(__pyx_v_mov_x);
  Py_DECREF(__pyx_v_mov_y);
  Py_DECREF(__pyx_v_whell);
  return __pyx_r;
}

/* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":27
 *   return n
 * 
 * def connec_state():             # <<<<<<<<<<<<<< 
 * 
 *   n = connection_state()
 */

static PyObject *__pyx_pf_9hidserver_connec_state(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9hidserver_connec_state(PyObject *__pyx_self, PyObject *unused) {
  PyObject *__pyx_v_n;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_v_n = Py_None; Py_INCREF(Py_None);

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":29
 * def connec_state():
 * 
 *   n = connection_state()             # <<<<<<<<<<<<<< 
 *   return n
 * 
 */
  __pyx_1 = PyInt_FromLong(connection_state()); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_1;
  __pyx_1 = 0;

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":30
 * 
 *   n = connection_state()
 *   return n             # <<<<<<<<<<<<<< 
 * 
 * def reConnect(src,dst):
 */
  Py_INCREF(__pyx_v_n);
  __pyx_r = __pyx_v_n;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("hidserver.connec_state");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  return __pyx_r;
}

/* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":32
 *   return n
 * 
 * def reConnect(src,dst):             # <<<<<<<<<<<<<< 
 * 
 *   n = reconnect(src,dst)
 */

static PyObject *__pyx_pf_9hidserver_reConnect(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_9hidserver_reConnect(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_src = 0;
  PyObject *__pyx_v_dst = 0;
  PyObject *__pyx_v_n;
  PyObject *__pyx_r;
  char *__pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"src","dst",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_src = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_dst = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_src, &__pyx_v_dst))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  return NULL;
  __pyx_L3:;
  Py_INCREF(__pyx_v_src);
  Py_INCREF(__pyx_v_dst);
  __pyx_v_n = Py_None; Py_INCREF(Py_None);

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":34
 * def reConnect(src,dst):
 * 
 *   n = reconnect(src,dst)             # <<<<<<<<<<<<<< 
 *   return n
 * 
 */
  __pyx_1 = PyString_AsString(__pyx_v_src); if (unlikely((!__pyx_1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_dst); if (unlikely((!__pyx_2) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(reconnect(__pyx_1, __pyx_2)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_3;
  __pyx_3 = 0;

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":35
 * 
 *   n = reconnect(src,dst)
 *   return n             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  Py_INCREF(__pyx_v_n);
  __pyx_r = __pyx_v_n;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("hidserver.reConnect");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  Py_DECREF(__pyx_v_src);
  Py_DECREF(__pyx_v_dst);
  return __pyx_r;
}

/* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":38
 * 
 * 
 * def quit_server():             # <<<<<<<<<<<<<< 
 *   
 *   n = quit_serv()
 */

static PyObject *__pyx_pf_9hidserver_quit_server(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9hidserver_quit_server(PyObject *__pyx_self, PyObject *unused) {
  PyObject *__pyx_v_n;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_v_n = Py_None; Py_INCREF(Py_None);

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":40
 * def quit_server():
 *   
 *   n = quit_serv()             # <<<<<<<<<<<<<< 
 *   return n
 * 
 */
  __pyx_1 = PyInt_FromLong(quit_serv()); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_1;
  __pyx_1 = 0;

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":41
 *   
 *   n = quit_serv()
 *   return n             # <<<<<<<<<<<<<< 
 * 
 * def quit():
 */
  Py_INCREF(__pyx_v_n);
  __pyx_r = __pyx_v_n;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("hidserver.quit_server");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  return __pyx_r;
}

/* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":43
 *   return n
 * 
 * def quit():             # <<<<<<<<<<<<<< 
 * 
 *   quit_thread()
 */

static PyObject *__pyx_pf_9hidserver_quit(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9hidserver_quit(PyObject *__pyx_self, PyObject *unused) {
  PyObject *__pyx_r;

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":45
 * def quit():
 * 
 *   quit_thread()             # <<<<<<<<<<<<<< 
 * 
 */
  quit_thread();

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"init_hidserver", (PyCFunction)__pyx_pf_9hidserver_init_hidserver, METH_NOARGS, 0},
  {"send_event_key", (PyCFunction)__pyx_pf_9hidserver_send_event_key, METH_VARARGS|METH_KEYWORDS, 0},
  {"send_mouse_ev", (PyCFunction)__pyx_pf_9hidserver_send_mouse_ev, METH_VARARGS|METH_KEYWORDS, 0},
  {"connec_state", (PyCFunction)__pyx_pf_9hidserver_connec_state, METH_NOARGS, 0},
  {"reConnect", (PyCFunction)__pyx_pf_9hidserver_reConnect, METH_VARARGS|METH_KEYWORDS, 0},
  {"quit_server", (PyCFunction)__pyx_pf_9hidserver_quit_server, METH_NOARGS, 0},
  {"quit", (PyCFunction)__pyx_pf_9hidserver_quit, METH_NOARGS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC inithidserver(void); /*proto*/
PyMODINIT_FUNC inithidserver(void) {
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("hidserver", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  /*--- Intern code ---*/
  /*--- String init code ---*/
  /*--- Builtin init code ---*/
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Function import code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  /*--- Execution code ---*/

  /* "/home/valerio/bluemaemo/trunk/test/hidserver.pyx":43
 *   return n
 * 
 * def quit():             # <<<<<<<<<<<<<< 
 * 
 *   quit_thread()
 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("hidserver");
}

static char *__pyx_filenames[] = {
  "hidserver.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
